<?php
/**
 * @category    Inchoo
 * @package     Inchoo_Facebook
 * @author      Ivan Weiler <ivan.weiler@gmail.com>
 * @copyright   Inchoo (http://inchoo.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="account-login facebook-login">
    
		<button rel="facebook-connect" type="button" title="<?php echo $this->__('Sign in with Facebook') ?>" class="button"><span><span><?php echo $this->__('Sign in with Facebook') ?></span></span></button>

</div>