<div id="category-bestseller">
    <div class="page-title featured-title">
        <h3><?php //echo $this->__('Best Sellers in') ?></h3>
    </div>

    <?php
        
        // some helpers
        $_helper = $this->helper('catalog/output');
        $storeId = Mage::app()->getStore()->getId();
        $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
        $themeHelper = $this->helper('themeadmin');
        $category_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
        $category = Mage::getModel('catalog/category')->load($category_id);
        //echo $category.'abc'; exit;
        $collection = Mage::getResourceModel('reports/product_collection')
            ->addOrderedQty()
            ->addAttributeToSelect('*')
            ->setStoreId($storeId)
            ->addStoreFilter($storeId)
            ->addCategoryFilter($category)
            ->setOrder('ordered_qty', 'desc');
        
        //Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
        //Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
        

        // if no products are currently featured, display some text
        if (!$collection->count()) :
    ?>

    <p class="note-msg"><?php echo $this->__('There are no featured products at the moment.') ?></p>

    <?php else : ?>


    <?php
        $_collectionSize = $collection->count();
        $_columnCount = 4;
        
        //Count panes
        $_paneCount = ceil($_collectionSize / $_columnCount); //Current number of rows (which means: number of tabs and panes)
        
        //Create random value. It will help to identify each instance of the slider.
        list($usec, $sec) = explode(' ', microtime());
        $randomSeed = (float) $sec + ((float) $usec * 100000);
        mt_srand($randomSeed);
        $r = mt_rand();
        
        
        $i = 0;
        ?>
<div class="itemslider-wrapper">

    <?php if($_paneCount > 1): ?>
        <a id="itemslider-back-<?php echo $r; ?>" class="backward browse-button" href="#">previous</a>
        <a id="itemslider-for-<?php echo $r; ?>" class="forward browse-button" href="#">next</a>
        <div class="custom_category_text"><?php echo $this->__('Best Sellers in').' '.$category->getName(); ?></div>
    <?php endif; ?> 
    <div id="itemslider-<?php echo $r; ?>" class="itemslider">         
        <?php
        $i=0;
        foreach ($collection as $_product) :
            $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
            //echo "<pre>"; print_r($_product->getPrice()); exit;
    ?>

        <?php if ($i++%$_columnCount==0): ?>
        <div class="slide">
        <ul class="products-grid spec-grid spec-grid5col grid-wide grid-actions-absolute grid-standalone clearer">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <div class="custom_author" style="font-size: 10px; font-style: italic;">
                    <a href="<?php echo $home_url.'catalogsearch/result/?q='.$_product->getResource()->getAttribute('author')->getFrontend()->getValue($_product); ?>">
                        <?php
                            // --------------- Custom code --------------------------
                               //echo 'Author: '.$_product->getAuthorName();
                               echo 'by '.$_product->getResource()->getAttribute('author')->getFrontend()->getValue($_product);
                            // --------------- Custom code --------------------------
          
                        ?>
                    </a>
                </div>
                <?php echo $this->getPriceHtml($_product, true) ?>
                
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </div>
        </ul>
        <?php endif ?>

        <?php endforeach ?>

        
       </div>
     </div>
     <script type="text/javascript">

    //<![CDATA[
      jQuery(function() {
        jQuery("#itemslider-<?php echo $r; ?>").cycle({
          fx: 'scrollHorz',
          easing: 'easeInOutCubic',
          timeout: <?php echo '1000';//intval($themeHelper->getCfg('product_slider/timeout')); ?>,
          speed: <?php echo intval($themeHelper->getCfg('product_slider/speed')); ?>,
          sync: 1,
          pause: 1,
          prev: "#itemslider-back-<?php echo $r; ?>",
          next: "#itemslider-for-<?php echo $r; ?>",
          manualTrump: 0,
          cleartypeNoBg: true
        });
      });
    //]]>
    </script>
    <?php endif ?>

</div>
