<?php
/**
 * @copyright  Copyright (c) 2011 Capacity Web Solutions Pvt. Ltd  (http://www.capacitywebsolutions.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style>
.productList { float:left; width:720px; }
.productList .product { background:#fff; border:1px solid #ccc; padding:5px; width:150px; float:left; margin:10px 8px 10px 0; text-align:center; }
.productList .product .cl { padding:0 0 0 30px; }
.productList .product .addCompare { float:left; clear:both; }
.productList .product .addWishlist { float:left; clear:both; }

</style>
<?php


$result = $this->getBestsellerProduct(); 
$itemPerRow = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 2 ;
 //getting product model
 $_helper = $this->helper('catalog/output');
$themeHelper = $this->helper('themeadmin');
$model = Mage::getModel('catalog/product');
$imgWidth = 141;
$imgHeight = 141;
$_collectionSize = count($result);
$_columnCount = 5;
//Count panes
    $_paneCount = ceil($_collectionSize / $_columnCount); //Current number of rows (which means: number of tabs and panes)
    
    //Create random value. It will help to identify each instance of the slider.
    list($usec, $sec) = explode(' ', microtime());
    $randomSeed = (float) $sec + ((float) $usec * 100000);
    mt_srand($randomSeed);
    $r = mt_rand();
?>

<div class="sectionHead"><h2><?php echo $this->getHeader(); ?></h2></div>

<div class="itemslider-wrapper">

    <?php if($_paneCount > 1): ?>
        <a id="itemslider-back-<?php echo $r; ?>" class="backward browse-button" href="#">previous</a>
        <a id="itemslider-for-<?php echo $r; ?>" class="forward browse-button" href="#">next</a>
    <?php endif; ?>
    <div id="itemslider-<?php echo $r; ?>" class="itemslider">   

<?php  $i=0;
for($cnt = 0; $cnt<count($result); $cnt++){
	
	$_product = $model->load($result[$cnt]); //getting product object for particular product id 
    ?>
	 <?php if ($i++%$_columnCount==0): ?>
                <div class="slide">
                <ul class="products-grid spec-grid spec-grid<?php echo $_columnCount;?>col grid-wide grid-actions-absolute grid-standalone clearer">
     <?php endif; ?>
     
            <li class="item<?php if(($i-1)%$itemPerRow==0): ?> first<?php elseif($i%$itemPerRow==0): ?> last<?php endif; ?>" <?php if($gridMinHeight) echo 'style="min-height:'.$gridMinHeight.'px;"'; ?>>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags ($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                
                    <img src="<?php echo $themeHelper->getImgUrl($this, $_product, $imgWidth, $imgHeight, 'small_image'); ?>" width="<?php echo $imgWidth;?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                
                    <?php // Code displaying product labels "new" and "sale". It's a copy of 'catalog/product/view/media_labels.phtml'
                    //require('view/media_labels.inc.phtml'); ?>
                
                </a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <div class="custom_author" style="font-size: 10px; font-style: italic;">
                    <a href="<?php echo $home_url.'catalogsearch/result/?q='.$_product->getResource()->getAttribute('author')->getFrontend()->getValue($_product); ?>">
                        <?php
                            // --------------- Custom code --------------------------
                               //echo 'Author: '.$_product->getAuthorName();
                               echo $_product->getResource()->getAttribute('author')->getFrontend()->getValue($_product);
                            // --------------- Custom code --------------------------
          
                        ?>
                    </a>
                </div>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist'); ?>"><?php echo $this->__('Add to Wishlist'); ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                           <!-- <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare'); ?>"><?php echo $this->__('Add to Compare'); ?></a></li>-->
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        
    <?php
			 if($i%$_columnCount==0 || $i==$_collectionSize): 
            ?>
                </ul>
                </div>
            <?php                
             endif;
        

}

?>
</div>
</div>
<script type="text/javascript">
//<![CDATA[
  jQuery(function() {
    jQuery("#itemslider-<?php echo $r; ?>").cycle({
      fx: 'scrollHorz',
      easing: 'easeInOutCubic',
      timeout: <?php echo '1000';//intval($themeHelper->getCfg('product_slider/timeout')); ?>,
      speed: <?php echo intval($themeHelper->getCfg('product_slider/speed')); ?>,
      sync: 1,
      pause: 1,
      prev: "#itemslider-back-<?php echo $r; ?>",
      next: "#itemslider-for-<?php echo $r; ?>",
      manualTrump: 0,
      cleartypeNoBg: true
    });
  });
//]]>
</script>
